
"""
HCI message ID
"""

# request the state of all the 3'rd part keys
ECS_HCI_GET_PROXY_INDICATION_STATE_REQUEST = 310
# reply to request the state of all the 3'rd part keys
ECS_HCI_GET_PROXY_INDICATION_STATE_REPLY = 311
ECS_HCI_SET_PROXY_INDICATION_STATE_REQUEST = 312
ECS_HCI_SET_PROXY_INDICATION_STATE_REPLY = 313
ECS_HCI_GET_PROXY_DISPLAY_STATE_REQUEST = 314
ECS_HCI_GET_PROXY_DISPLAY_STATE_REPLY = 315
ECS_HCI_SET_PROXY_DISPLAY_STATE_REQUEST = 316
ECS_HCI_SET_PROXY_DISPLAY_STATE_REPLY = 317
# request unsolicited transmission of Panel KeyStatus Replay when a key is updated
ECS_HCI_KEY_STATUS_AUTO_UPDATES_REQUEST = 318
# replay to request unsolicited transmission of Panel KeyStatus Replay when a key is updated
ECS_HCI_KEY_STATUS_AUTO_UPDATES_REPLY = 319
EHX_MSG_ID_KEY_STATUS_AUTO_UPDATES_REQUEST = 318
EHX_MSG_ID_KEY_PRESSED_STATUS_REQUEST = 320
EHX_MSG_ID_KEY_PRESSED_STATUS_REPLY = 321